In [4]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("..//Data/Final_data.csv")
contingency_table = pd.crosstab(
    df['Operator'],
    df['Call Drop Category'],
    margins = True
)
contingency_table

Call Drop Category  Call Dropped  Poor Voice Quality  Satisfactory     All
Operator                                                                  
Airtel                      4663               14092         30273   49028
BSNL                         634                1677          7074    9385
Idea                        1257                4443          7879   13579
MTNL                          48                  40           241     329
Other                         27                 677           345    1049
RJio                        5649               19226         66355   91230
Tata                          11                  35            34      80
Telenor                        1                   4             5      10
Vodafone                    1847                8334         21759   31940
All                        14137               48528        133965  196630

In [28]:
f_obs = np.append(contingency_table.iloc[0][0:3].values, contingency_table.iloc[1][0:3].values)
f_obs

array([ 4663, 14092, 30273,   634,  1677,  7074], dtype=int64)

In [29]:
f_obs = np.append(f_obs,contingency_table.iloc[2][0:3].values)
f_obs = np.append(f_obs,contingency_table.iloc[3][0:3].values)
f_obs = np.append(f_obs,contingency_table.iloc[4][0:3].values)
f_obs = np.append(f_obs,contingency_table.iloc[5][0:3].values)
f_obs = np.append(f_obs,contingency_table.iloc[6][0:3].values)
f_obs = np.append(f_obs,contingency_table.iloc[7][0:3].values)

In [30]:
f_obs

array([ 4663, 14092, 30273,   634,  1677,  7074,  1257,  4443,  7879,
          48,    40,   241,    27,   677,   345,  5649, 19226, 66355,
          11,    35,    34,     1,     4,     5], dtype=int64)

In [10]:
row_sums = contingency_table.iloc[0:8,3].values
row_sums

array([49028,  9385, 13579,   329,  1049, 91230,    80,    10],
      dtype=int64)

In [11]:
col_sums = contingency_table.iloc[8,0:3].values
col_sums

array([ 1847,  8334, 21759], dtype=int64)

In [12]:
total = contingency_table.loc['All', 'All']

f_expected = []
for j in range(8):
    for i in col_sums:
        f_expected.append(i*row_sums[j]/total)
f_expected

[460.5335706657173,
 2078.011249555002,
 5425.41957992168,
 88.15590194782078,
 397.7754666124193,
 1038.5404821237858,
 127.55130448049637,
 575.5346895183848,
 1502.6469053552357,
 3.090388038447846,
 13.94439302242791,
 36.40701317194731,
 9.8535472715252,
 44.46099781315161,
 116.08193561511469,
 856.9486344911763,
 3866.7081320246148,
 10095.476631236332,
 0.7514621370085949,
 3.390733865635966,
 8.85276916035193,
 0.09393276712607436,
 0.42384173320449575,
 1.1065961450439912]

In [13]:
dof = (len(row_sums)-1)*(len(col_sums)-1)
print("Degrees of Freedom: {}".format(dof))

Degrees of Freedom: 14


DoF=(Number of rows−1)∗(Number of columns−1)

In [31]:
f_obs

array([ 4663, 14092, 30273,   634,  1677,  7074,  1257,  4443,  7879,
          48,    40,   241,    27,   677,   345,  5649, 19226, 66355,
          11,    35,    34,     1,     4,     5], dtype=int64)

In [32]:
chi_squared_statistic = ((f_obs - f_expected)**2/f_expected).sum()
print('Chi-squared Statistic: {}'.format(chi_squared_statistic))

Chi-squared Statistic: 740437.8688552484


In [3]:
from scipy.stats import chi2
alpha=0.05
dof=14
critical_value=chi2.ppf(q=1-alpha,df=dof)
print('critical_value:',critical_value)

critical_value: 23.684791304840576


X^2=(observed−expected)^2 / (expected)

Since it is very high p will be very less than 0.05(close to zero) so call drop quality and operator are statistically dependant